// +build !skippackr
// Code generated by github.com/gobuffalo/packr/v2. DO NOT EDIT.

// You can use the "packr2 clean" command to clean up this,
// and any other packr generated files.
package packrd

import (
	"github.com/gobuffalo/packr/v2"
	"github.com/gobuffalo/packr/v2/file/resolver"
)

var _ = func() error {
	const gk = "87bf23833196d7cf6e25798a808c1f4e"
	g := packr.New(gk, "")
	hgr, err := resolver.NewHexGzip(map[string]string{
		"7ea71707e43a9caee86287c325676b79": "1f8b08000000000000ff8c5241729c3010bceb1573f456e21770cd1772a684d4c0c4624446a3acc9eb53408a62f196cb3750f7744bddf3fa4adf261ed41be8e7ec5c50ac9fe6bb04926cdc73f0c6590abd3822228ed4f150a0ec13cdca93d785deb07cdfd07d3cb6dec87842313fcd74671b73dd4fe86f964d98a4a64411bdafc928545588b5c7d02e57c288581362db67fd92e23e6779e6408677fb00bc413660ff9f95b3b22dc472a586d18b209dc8134af103e857c9d21d6c776b8ed8aaf0ef0a6289787f4cafdd9cdb90a598fad52dcb25df5a5806ea4c017ad9e837ba8f50fcbf3597c3b3b9141591f80f94f1b596cebe2dc787c793a2874202cab57f8eb7f5d61109060abe041fb12b461463d988cf623fc1ad2d339e718a79abe529b26ec6e71bb59570dee51ff92ece45cdf387889af3f1c3131be7fe050000ffff2261c5a310030000",
	})
	if err != nil {
		panic(err)
	}
	g.DefaultResolver = hgr

	func() {
		b := packr.New("migrations", "./migrations")
		b.SetResolver("001_initial.sql", packr.Pointer{ForwardBox: gk, ForwardPath: "7ea71707e43a9caee86287c325676b79"})
		}()

	return nil
}()
