// +build !skippackr
// Code generated by github.com/gobuffalo/packr/v2. DO NOT EDIT.

// You can use the "packr2 clean" command to clean up this,
// and any other packr generated files.
package packrd

import (
	"github.com/gobuffalo/packr/v2"
	"github.com/gobuffalo/packr/v2/file/resolver"
)

var _ = func() error {
	const gk = "87bf23833196d7cf6e25798a808c1f4e"
	g := packr.New(gk, "")
	hgr, err := resolver.NewHexGzip(map[string]string{
		"7ea71707e43a9caee86287c325676b79": "1f8b08000000000000ff9453c196db200cbcf3153a26afd92fc8b5bfd0338f80e2a88b852b44b3eed7f7d9a42e78b7697bb32598d1cc889717f834d2204e11be4cc678c1e553dd252204cc4aec941267381800000a70a121a3908b30098d4e6678c5f9b476759e1014df1438297089b1d61ba0be6d8ee78db3307d2b08c401df3a6abbc0da1623713f5bc9c4035c5410e1b09c3e35ed86a2cae2a47425ff1fbaeaf5609d82d28859dd38c19df4964aadc08fc4b8a982805757a2822f22c86ab74b152efb1b861231d86b927f427cd89b26f21ff9abe915abb3f53f26ef223685492809e90cc4efb389f41d65b65b78b53e62ce6e40f89a135ffe1e5867aa5d07b23e7156710b67e29ded7d64cbf123dc6f28f8104379e3dce7b74d9cd569c9f82bc396c052e8b482e01505d963dee74fe158172aa2227897bd0bf86e6f9f01f6efe4095eb35870d88d7bdab11d1fbbb26afc28f4bc6cd6f38d5cd332a67de49fd39d8d0992a63fb9796ebb9d57e7fede6fd167637e060000ffffd8bff2a549040000",
	})
	if err != nil {
		panic(err)
	}
	g.DefaultResolver = hgr

	func() {
		b := packr.New("migrations", "./migrations")
		b.SetResolver("001_initial.sql", packr.Pointer{ForwardBox: gk, ForwardPath: "7ea71707e43a9caee86287c325676b79"})
		}()

	return nil
}()
